BULK_CATEGORY_PROMPT = (
    "Classify the following purchase items into one of these categories: {tags}.\n"
    "Items: \"{items}\"\n"
    "Return a dictionary mapping each item to its category."
    "Example output: {{\"item1\": \"category1\", \"item2\": \"category2\"}}"
    "Always return valid JSON ready to be parsed, without any markdown or other text around it."
)
ESSENTIALITY_PROMPT = (
    "You are evaluating how essential a purchase is for everyday life needs.\n"
    "Rate each item on a scale from 0 to 10:\n"
    "  0 = completely non-essential or luxury\n"
    "  5 = moderately useful but not strictly necessary\n"
    " 10 = absolutely essential for basic living (e.g., food, medicine, hygiene)\n\n"
    "Items: \"{items}\"\n\n"
    "Guidelines:\n"
    "- If multiple items are listed, average their essentiality logically.\n"
    "- If an item is unknown, vague, or not clearly a necessity, assign a lower score.\n"
    "- For food or drinks, consider nutritional value, necessity, and indulgence level.\n"
    "- For services or durable goods, consider their role in daily functioning or safety.\n"
    "- Always return only a single integer between 0 and 10.\n\n"
    "Output format: a single number only (no words, no explanations).\n"
    "Examples:\n"
    "  'bread' → 9\n"
    "  'soda' → 2\n"
    "  'premade food' → 4\n"
    "  'chocolate/junkfood' → 3\n"
    "  'meat/chicken' → 10\n"
)
